### ISSUE TITLE
filter classrooms

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#17]
Make the filters "All classes", "Active classes" and "Finished classes" functional

![Skjermbilde 2024-05-02 kl  23 41 45](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/90150033/c9d21f96-f6d3-46bc-a064-a9da3dcb4996)

**Comment by Jonhels** [comment]
Added search on classroom name, filtering, updated edit for finished status, updated backend controller and schema for edit classroom. The filters "All classes", "Active classes" and "Finished classes"  are now functional.
