### ISSUE TITLE
forgot password

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#26]
Not priority, but if time, add a forget password function where the user maybe receives a code to verify on email and then makes a new password?

![Skjermbilde 2024-05-03 kl  00 13 44](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/90150033/a2f3a9fc-9766-4dcb-a29d-714075b5e545)

**Comment by maheggh** [comment]
completed
