### ISSUE TITLE
achievements section

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#30]
On the achievements page, add statistics/progress of how many post/reflections the student have.
Also add some kind of achievements (game/levels). 
For example:
-first reflection made public, achievement/level 1 is unlocked
-first feedback from teacher, new achievements
-3 likes on a post, new acheievements
-received 3 feedbacks from teacher
-made 5 reflections public
-joined a classroom
-answered the sustainability fact poll
-logged in 5 days in a row
-visited/read through the FAQ/help page?
-clicked a link on the sustainability info page
-liked another students reflection
-made the top 5 on most liked reflection post
etc

**Comment by Hannah-Sofie** [comment]
Maybe when the student have fullfilled all task/achievements they get some kind of diploma?

**Comment by Hannah-Sofie** [comment]
maybe add a top post scoreboard or something, with top 10, top 5? most liked pubic posts/reflections

**Comment by maheggh** [comment]
The achievements has been added, and leaderboard created.
![asdacasdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/111765195/f1396497-6cb2-474c-b100-37e70d9089db)

**Comment by maheggh** [comment]
branch:
https://github.com/Hannah-Sofie/SustainabilityDiary/tree/achievements
