### ISSUE TITLE
labels, filter/sort classroom

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#32]
Add some kind of search, filtering for classroom. Maybe search for a classroom, add labels to classroom to categories them? Filter after name, category, recently opened?

![Skjermbilde 2024-05-03 kl  00 26 09](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/90150033/39cb8c90-27e8-42a9-8d6e-7ea208445219)

**Comment by Jonhels** [comment]
Added search, but no labels yet. Will look at labels, but need to find out the best way to do them.

**Comment by Jonhels** [comment]
Have to ask group about labels and thoughts around that first

**Comment by Jonhels** [comment]
Dropping labels with the exception of finished and active labels and favorites. Inspiration from blackboard. Search is implemented

**Comment by Jonhels** [comment]
search on names, closing this since we decided to not have labels
