### ISSUE TITLE
add a favorite icon to classroom

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#34]
add afavorite button (star icon?) to classroom, so students and teacher can favorite classrooms

![Skjermbilde 2024-05-03 kl  00 30 57](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/90150033/edea850a-12a7-4eba-a6af-085f299bc871)

**Comment by hakonrh** [comment]
Pushet til branch favouriteClassroom. Knapp for å legge klasserom til som favoritt ligger inne på classroomDetail. På backend er det lagt til favoritt på classroomSchema, favouriteClassroom funksjon på classroomController som er eksportert og lagt til i classroomRoutes. Når du prøver å bruke funksjonen får error 404. Usikker på hva den ikke finner, kanskje bruker ID?
