### ISSUE TITLE
save updated reflection

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#74]
When editing/updating a reflection and saving, error, fix bug

![Skjermbilde 2024-05-09 kl  01 15 23](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/90150033/1154a7bb-ea51-4160-86e9-a64b83a2388f)

**Comment by Jonhels** [comment]
Fixed reflection but when updating. Problem was with middleware and routes for handeling multipart/formdata. Will close after testing properly with updating everything. For now it works and i will merge what i have until now into main from branch.

**Comment by Jonhels** [comment]
This is now completed
