### ISSUE TITLE
refresh problem

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#77]
When logged in and refresh page, the user gets logged out, fix problem so that the user stays logged in even if they refreshes the page

![Skjermbilde 2024-05-09 kl  01 22 49](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/90150033/00bff665-74f9-4add-a5e4-184ae5f3fcbe)

**Comment by maheggh** [comment]
const user = await User.findById(req.user.id).select("-password");
replaced with
const user = await User.findById(req.user._id).select("-password");
solved the issue.
